### ISSUE TITLE
[data sources]

### ISSUE THREAD

**Issue by Adafede** [gnames/gnverify#17]
Hi, me again

Don't know if I am posting this at the right place but had recently such kind of issues:

`echo "Fusarium verticillioides" | gnverify -s 11,179,5 -f pretty`

As it is a Fungi sp. I am used to trusting more Index Fungorum (5) but its entries seem a bit outdated (2012-02-09) when compared to others updated in 2020.
Other DB so return the correct current name where Index Fungorum returns an old one.
This leads so to :
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=417365, which is an old entry instead of http://www.speciesfungorum.org/Names/SynSpecies.asp?RecordID=314213

You told me you would be releasing a lot of new things mid January, so don't know if relevant...in case just ignore! :)

Again, thank you for your impressive work and the responsiveness you put in it! 👍🏼

**Comment by dimus** [comment]
Sadly there was no place where I could automatically download updated index fungorum, so this was a process to update it:

-  Paul Kirk exchange a few letters
-  He sends me a file in a format that was a bit different from the previous file
- I write a custom  importer and get IF into the system

As you can imagine, it was not a very optimized way of doing things. As a result, Index Fungorum became outdated. I will write to Paul, and see if there is a better way now, that he is working with Kew.

**Comment by dimus** [comment]
https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/33

**Comment by dimus** [comment]
Index Fungorum is updated and now returns:

```json
{
      "dataSourceId": 5,
      "dataSourceTitleShort": "Index Fungorum",
      "curation": "Curated",
      "recordId": "314223",
      "outlink": "http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID=314223",
      "entryDate": "2021-01-07",
      "matchedName": "Fusarium verticillioides (Sacc.) Nirenberg 1976",
      "matchedCardinality": 2,
      "matchedCanonicalSimple": "Fusarium verticillioides",
      "matchedCanonicalFull": "Fusarium verticillioides",
      "currentRecordId": "314213",
      "currentName": "Fusarium fujikuroi Nirenberg 1976",
      "currentCardinality": 2,
      "currentCanonicalSimple": "Fusarium fujikuroi",
      "currentCanonicalFull": "Fusarium fujikuroi",
      "isSynonym": true,
      "classificationPath": "Fungi|Ascomycota|Sordariomycetes|Hypocreales|Nectriaceae|Fusarium fujikuroi",
      "classificationRanks": "kingdom|phylum|class|order|family|",
      "editDistance": 0,
      "stemEditDistance": 0,
      "matchType": "Exact"
    }
```

**Comment by Adafede** [comment]
you are amazing!
