### ISSUE TITLE
Help with error

### ISSUE THREAD

**Issue by Jegelewicz** [gnames/gnverify#18]
@dimus I tried following the instructions in use-gnverify-windows.pdf and when I got to this point:

> You will see the PowerShell terminal window. Type the following commands:
> cd ~\bin
> gnverify "Plantago major"
> After a short delay, you should see a result printed on the screen as a comma-separated value output. 

I received this message:

![image](https://user-images.githubusercontent.com/5725767/104051194-fd3c3580-51a4-11eb-888d-51dccf6963ff.png)

Any insight into what I am doing wrong?

**Comment by mjy** [comment]
@Jegelewicz 

Did you open a new powershell after these steps?

```
copy path_to\gnverify.exe C:\Users\your_username\bin

Add C:\Users\your_username\bin directory to your PATH environment variable.
```

**Comment by dimus** [comment]
@Jegelewicz 

Make sure that gnverify.exe is located in ~/bin directory, and `cd ~/bin` and try:

```
./gnverify "Plantago major"
```
note `./`

**Comment by dimus** [comment]
I did try from PowerShell
```
cd ~/bin
gnverify "Plantago major"
``` 

and I did get the same error as you. Looks like Windows changed its settings and now it is required to use
`./gnverify` instead.

**Comment by dimus** [comment]
I updated PDF instructions

**Comment by Jegelewicz** [comment]
Apologies for being a super-novice! But it still seems like something isn't quite working.

![image](https://user-images.githubusercontent.com/5725767/104061525-fe299300-51b5-11eb-8891-7e83b170280b.png)

Here is what my bin directory looks like after I have extracted the files:

![image](https://user-images.githubusercontent.com/5725767/104061575-18fc0780-51b6-11eb-92d1-ff85d5281e42.png)

even within the nested folder that the unzip creates, I do not directly see what is shown in the PDF

![image](https://user-images.githubusercontent.com/5725767/104061650-392bc680-51b6-11eb-9650-1740a4093fdb.png)

It seems like the application is buried somewhere, but I don't find the gnverify application file anywhere in the unzipped files. Or I have done something wrong earlier in the process?

**Comment by Jegelewicz** [comment]
Wait! I figured it out! I downloaded the wrong zip file...

**Comment by dimus** [comment]
:+1: 
I noticed that PDF gives some outdated examples. Lets find out if it makes sense to change documentation, or add the commands back. At the moment gnverify reads from a file with only names, one per line, and does not try to read tab-separated, or comma-separated files.

**Comment by Jegelewicz** [comment]
OK, now that I have the right stuff, I cannot get it to do anything and possibly that is because of

> gnverify reads from a file with only names, one per line, and does not try to read tab-separated, or comma-separated files.

but I'm not sure. Here is what I entered.

![image](https://user-images.githubusercontent.com/5725767/104064365-12bc5a00-51bb-11eb-9ed3-f13518e5f8c9.png)

The results file is just this:

![image](https://user-images.githubusercontent.com/5725767/104064487-48f9d980-51bb-11eb-877f-9b2f0d4c436f.png)

[Lice name verification.txt](https://github.com/gnames/gnverify/files/5789366/Lice.name.verification.txt)

**Comment by dimus** [comment]
Let me try to run it, the text itself looks good
