### ISSUE TITLE
Instructions to find list of sources needs an update

### ISSUE THREAD

**Issue by Jegelewicz** [gnames/gnverify#20]
the help function provides the following information:

  such matches are returned in "preferred_result" results.
                                To find IDs refer to "https://resolver.globalnames.org/resources".

but the actual site for the list is at https://resolver.globalnames.org/data_sources

**Comment by dimus** [comment]
Thank you for spotting the bad link @Jegelewicz, I fixed it in the code and updated link will appear when the new version of gnverify will be released (sometime this week)
