### ISSUE TITLE
Results in csv?

### ISSUE THREAD

**Issue by Jegelewicz** [gnames/gnverify#21]
Any chance you could make results from https://resolver.globalnames.org/ available in csv?

**Comment by dimus** [comment]
@Jegelewicz  I am not sure I understood what would you need as a csv file? There are several options. First, when I move data from old (resolver.globalnames.org) to new (verifier.globalnames.org) I do it by generating huge csv files, that contain only information that I need for conversion. Also, for every data-source that I update I generate DwCA file, which I can release for public at opendata.globalnames.org

**Comment by Jegelewicz** [comment]
When I run a list of names through https://resolver.globalnames.org/ I get a pretty report that looks great, but isn't super useful. I can download that report in JSON or XML, but neither of those are super useful to me (as someone who does not know how to manipulate those things).

When I run the same list of names through
```
PS C:\Users\Teresa\bin> ./gnverify ..\data\Acari.txt > ..\data\Acari.csv
```
I get a file that I can easily parse into distinct columns, which helps me make decisions in bulk (I feel confident using names with an Exact Match).

I'd like to be able to get that file without the command line. Does that make sense?

**Comment by dimus** [comment]
Now  I understood, and yes, it would definitely be useful. When I get to making a website for verifier globalnames.org, it will definitely have CSV as an option. As for resolver.globalnames.org, it is an aging piece of software that is going to be deprecated when verifier.globalnames.org will have all the features of it. Taking in account of the number of other projects I do need to set priorities, and it incorporating new features to resolver.globalnames.org is not where I can go. Sadly we will have to wait until verifier.globalnames.org will get its web-interface.

**Comment by dimus** [comment]
I added a ticket to make gnverify to be accessible via web as well.

https://github.com/gnames/gnverify/issues/23

**Comment by dimus** [comment]
@Jegelewicz I adjusted web-page from resolver.globalnames.org to https://verifier.globalnames.org
Please let me know if it works for you.

**Comment by Jegelewicz** [comment]
@dimus THANKS!!!

I tried the web interface to csv with CoL and WoRMS as preferred, with a list of over 500 names and got this:

> Secure Connection Failed
> 
> An error occurred during a connection to verifier.globalnames.org. PR_CONNECT_RESET_ERROR
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

so I hit try again and got:

> 414 Request-URI Too Large
> nginx/1.14.2

So I started slow with a list of 10 names and the same advanced options. This worked, but the results are displayed in csv format on my screen. I sort of expected to get a file there. Possible? I can copy the screen into Excel and parse, but that seems a bit primitive.

![image](https://user-images.githubusercontent.com/5725767/110956644-12018a80-8308-11eb-8133-0e4bd591fea0.png)

I assume the web version will be limited to some degree due to timeouts, it might be good to try to figure that limit out and warn users about it. I might be able to do that as I work with it - I'll keep you posted.

**Comment by dimus** [comment]
@Jegelewicz something around 300 names should work for Firefox or Chrome

Yes, you are right that such information should be on the home page!

As for the limit itself, there are pluses and minuses to that. If data are provided in URL, browsers will limit the URL size. A huge plus of this approach is that if a user wants to share their experience, they just copy the URL, and another person can repeat exactly the same request. I found it very useful for communication purposes at https://parser.globalnames.org, and I would try to keep the same at https://verifier.globalnames.org unless I find that it is more of a hindrance for users.

It is possible to use POST requests. Then data is sent not via URL but in a "body" of request. Such an approach significantly increases the size of requests, but communication between users becomes less convenient.

Also, it seems that when a service runs locally, the limit (at least for Firefox) is much bigger. When I tested gnverify on my machine, I could load 1000+ names at once.

Saving results from CSV or JSON as a file is definitely possible, however, it adds another level of complexity - gnverify would need to store results temporarily, and delete old results regularly. My current approach to the web interface is more like interactive play with data, than heavy-duty usage, but I might be mistaken! I would need to gather feedback, and see if limitations of this approach go against of real world usage. Your feedback is definitely makes me think POST approach might be a better alternative.

**Comment by Jegelewicz** [comment]
> A huge plus of this approach is that if a user wants to share their experience, they just copy the URL, and another person can repeat exactly the same request.

Yeah - I can see that being a plus! However, as things change at the source (CoL, WoRMS, etc.) wouldn't the results change as well?

> POST approach might be a better alternative.

I know that people are all about instant gratification, but for a huge list of names, I would definitely be willing to wait for the result. However, I might be the only person who needs that functionality. We are working on a project with thousands of names that need verification. They are split out into distinct groups, but even those have more than 1,000 names each. As we continue to refine our process, I'll let you know if we run into a roadblock.

**Comment by dimus** [comment]
I am leaning towards a move to POST for now and setting 5k names limit on the system https://github.com/gnames/gnverify/issues/38

**Comment by dimus** [comment]
@Jegelewicz now web user interface is using POST and 5k names limit at
https://verify.globalnames.org
