### ISSUE TITLE
As a User I want to see cardinality of matched name

### ISSUE THREAD

**Issue by dimus** [gnames/gnverify#7]
Cardinality allows quickly asses how successful a match was

**Comment by dimus** [comment]
I will not do it for now, there are 3 cardinalities, of the input, match and currently accepted name. To add them all it a lot more info for csv, I suspect we can leave it for now, and return to it when there is a known usecase.

**Comment by mjy** [comment]
As a user I typically know the input.  How about only providing the info if there is a difference between match/current?

**Comment by dimus** [comment]
Cardinality of all 3 cases is already provided through JSON output (--format compact or --format pretty), This issue was about adding cardinality to CSV output (--format csv), and I decided to wait until someone actually needs it for CSV output.
